# Generated by Django 6.0.7 on 2026-08-04 18:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('window_start', models.DateTimeField()),
                ('period_seconds', models.PositiveIntegerField(default=60)),
            ],
            options={
                'verbose_name': 'rate limit bucket',
                'verbose_name_plural': 'rate limit buckets',
            },
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(default='Untitled game', max_length=80),
        ),
        migrations.AlterField(
            model_name='pendinggame',
            name='title',
            field=models.CharField(default='Untitled game', max_length=80),
        ),
        migrations.CreateModel(
            name='SignupApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved (verification sent)'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('closed_beta', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_signups', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signup_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'signup application',
                'verbose_name_plural': 'signup applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
